sudo: required
dist: trusty
language: go
go:
    - 1.5
    - 1.6.3
    - 1.7
    - tip
addons:
  apt:
    sources:
    - sourceline: 'ppa:snappy-dev/tools'
    packages:
    - snapcraft
before_script:
  - ssh-keygen -t rsa -b 4096 -C "localhost@localhost" -q -N ""
script:
    - make build
    - make check
    - make bench
    - make all -j4
    - make dist -j4
    - make package
