language: go
go:
- 1.6
- 1.9.1
- tip
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
      key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
    - bazel
script:
- make tools
- make deps
- make build -j4
- make all -j4
- make test-all -j4
- make dist -j4
- bazel build //...
- bazel test //...
deploy:
  provider: releases
  api_key:
    secure: J8P3HFbyp7gkGJPMMKVbcLKt7HywiyblL+xPXLYxhXcY33aZP01HpU37kD6n8XvnHdWR5SELdFJiLYeoSy9cz6oU6zLNTTXJoat+6F/WBJfJY132NbyK7geH4HtE6mvekrMNKe49PLD91zpN7441qFrUfEmY4+f1pqREClzm0KpJDNIdPdHrrJAup4vLdsCf5dTpy8HQ2y1pnPi8OMZKHQ+p85fhSaey+P3x2xsD569BHsHq99qXs9psp8y+iXMJZ7uaOEBFxd//8apmZDMOS26CTwQ1nxOFagh27dA6AiRU1U4EyCu7O+iTsEVu9XgTLZ53D5/AG075mCagu3A/l+BojBs9afCjs8XmkpbSG/e2Gqkrn2RTpLF9DKlGtp+jB93SNVfdFKgngbfSqyRlFx/xHIWNlV7bd/MBq/MF96fdYcNbuKhf+OcIhXhLnNbYI9t2/+6UHOv5L8cwlD9ifzLAsttoaeBh4O1Sv8Kf0itf9OyMESAorEVVTZ8Np2Rx5rwy9YoLh40fGW5UTELJRLapzU+seO/iA8gWHFYVKJbRvo0QK3EVJCJB39DsiAhXPHE80pPQsPfhtsvhK8GaPEkw4gKbyojjnCw39PEbOD5HwwHxqUzG3LfTk96YRxLF58pfwdnc+ESfjZB1CCXvMS70Wae53c+LDGNz+hTTQ2I=
  file:
    - release/server-386
    - release/server-arm
    - release/server-amd64
    - release/server-386.exe
    - release/server-amd64.exe
  skip_cleanup: true
  on:
    tags: true
    repo: jeremyje/gowebserver
