.TH GOWEBSERVER 1
.SH NAME
gowebserver \- Standalone HTTP/HTTPS web server to host files on your
filesystem.
.SH SYNOPSIS
.B gowebserver
.SH DESCRIPTION
.B gowebserver
hosts files from any directory on your filesystem via HTTP and HTTPS.
It is a zero configuration application and will also generate a self-signed
certificate automatically.
.SH OPTIONS
.IP -certificate
Certificate to host HTTPS with. (default "cert.pem")
.IP -certificate_duration
Certificate valid duration. (default 365)
.IP -directory
The directory to serve.
.IP -generate_cert
Only generate a self-signed certificate for the server.
.IP -host
Comma-separated hostnames and IPs to generate a certificate for.
.IP -port
Port to run HTTP server. (default 8080)
.IP -private_key
Certificate to host HTTPS with. (default "rsa.pem")
.IP -secure_port
Port to run HTTPS server. (default 8443)
.SH AUTHOR
Jeremy Edwards (jeremyje@gmail.com)
