name: gowebserver
version: 1.7
summary: Go Web Server
description: Standalone HTTP/HTTPS web server to host files on your file system.
type: app
confinement: strict
icon: snap/gui/icon.png
grade: devel

apps:
  gowebserver:
    command: gowebserver

parts:
  gowebserver:
    source: .
    plugin: go
    go-packages:
    - github.com/elazarl/go-bindata-assetfs
    - gopkg.in/yaml.v2
    - github.com/prometheus/client_golang/prometheus
    - github.com/rs/cors
    go-importpath: github.com/jeremyje/gowebserver
