name: gowebserver
version: 1
summary: Go Web Server
description: Standalone HTTP/HTTPS web server to host files on your file system.
confinement: strict
icon: packaging/setup/gui/icon.png
vendor: Jeremy Edwards <jeremyje@gmail.com>

apps:
  gowebserver:
    command: gowebserver --config.file=/var/lib/gowebserver.yaml
    daemon: simple
    plugs:
    - network-bind

parts:
  gowebserver:
    plugin: make
    source: .
    makefile: Makefile
    make-parameters: [build]
    artifacts:
    - gowebserver
    filesets:
      config:
        - var/lib/gowebserver/