name: gowebserver
version: 1.7
summary: Go Web Server
description: Standalone HTTP/HTTPS web server to host files on your file system.
type: app
confinement: strict
icon: snap/gui/icon.png
grade: devel

apps:
  gowebserver:
    command: gowebserver

parts:
  gowebserver:
    plugin: make
    source: .
    makefile: Makefile
    make-parameters: [snapbuild]
    artifacts:
    - gowebserver
