name: gowebserver
version: 1.8
summary: Go Web Server
description: Standalone HTTP/HTTPS web server to host files on your file system.
type: app
confinement: strict
icon: snap/gui/icon.png
grade: devel

apps:
  gowebserver:
    command: gowebserver

parts:
  gowebserver:
    plugin: make
    source: .
    makefile: Makefile
    make-parameters: [gowebserver]
    prepare: |
      make install-go
      echo "SYSTEM VARS!!"
      echo "> PATH"
      echo $PATH
      echo "> GOPATH"
      echo $GOPATH
      echo "> GOROOT"
      echo $GOROOT
      make tools
      make deps
      echo "> FINDING"
      find / -type f -print
    artifacts:
    - gowebserver
