# Copyright 2026 Jeremy Edwards
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.9'
services:
  gowebserver-standalone:
    image: docker.io/jeremyje/gowebserver:v3.2.3
    container_name: gowebserver-standalone
    hostname: gowebserver-standalone
    networks:
      - gowebserver-standalone-net
    command:
      - '-configfile=/etc/gowebserver/gowebserver.yaml'
    user: root
    ports:
      - 28082:8080
      - 28083:8443
    #restart: on-failure
    volumes:
      - ./gowebserver:/etc/gowebserver
      - gowebserver_standalone_data:/gowebserver/upload
volumes:
  gowebserver_standalone_data:
networks:
  gowebserver-standalone-net:
    driver: bridge
