---
# Source: gowebserver/templates/gowebserver.yaml
# Copyright 2022 Jeremy Edwards
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Service
apiVersion: v1
metadata:
  name: "gowebserver"
  namespace: default
  labels:
    app: "gowebserver"
    component: gowebserver
    release: gowebserver
spec:
  selector:
    app: "gowebserver"
    component: gowebserver
    release: gowebserver
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
  - name: https
    protocol: TCP
    port: 8443
---
# Source: gowebserver/templates/gowebserver.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gowebserver"
  namespace: default
  labels:
    app: "gowebserver"
    component: gowebserver
    release: gowebserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "gowebserver"
  template:
    metadata:
      labels:
        app: "gowebserver"
    spec:
      containers:
      - name: gowebserver
        image: "docker.io/jeremyje/gowebserver:v3.2.1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
