{
 "title": "Web Server",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_host, http_server_name) (rate(http_server_duration_count[$__rate_interval]))",
     "legendFormat": "{{http_host}}{{http_server_name}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_server_name, http_host) (rate(http_server_duration_bucket[$__rate_interval])))",
     "legendFormat": "{{http_host}}{{http_server_name}}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(uploaded_files_total[$__rate_interval]))",
     "legendFormat": "Files"
    },
    {
     "expr": "sum(rate(uploaded_bytes_total[$__rate_interval]))",
     "legendFormat": "Data Rate"
    }
   ]
  },
  {
   "title": "Response Content Length",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(http_server_name) (rate(http_server_response_content_length[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}