name: gowebserver
version: 1
#vendor: Jeremy Edwards <jeremyje@gmail.com>
summary: Go Web Server
description: Standalone HTTP/HTTPS web server to host files on your file system.
icon: setup/gui/icon.png
confinement: strict

apps:
  gowebserver:
    command: bin/gowebserver.git --config.file=/var/lib/gowebserver.yaml
    daemon: simple

parts:
  gowebserver:
    plugin: go
    source: git@bitbucket.org:futonredemption/gowebserver.git
    filesets:
      config:
        - var/lib/gowebserver/
