name: gowebserver
version: 1
summary: Go Web Server
description: Standalone HTTP/HTTPS web server to host files on your file system.
confinement: strict

apps:
  gowebserver:
    command: gowebserver

parts:
  gowebserver:
    plugin: make
    source: ..
    makefile: Makefile
    make-parameters: [build]
    artifacts:
    - gowebserver