name: gowebserver
version: 1
summary: Go Web Server
description: Standalone HTTP/HTTPS web server to host files on your file system.
icon: icon.png
confinement: strict

apps:
  gowebserver:
    command: bin/gowebserver.git --config.file=/var/lib/gowebserver.yaml
    daemon: simple

parts:
  gowebserver:
    plugin: go
    source: git@github.com:jeremyje/gowebserver.git
    filesets:
      config:
        - var/lib/gowebserver/
